### ISSUE TITLE
Continued support

### ISSUE THREAD

**Issue by Schoonology** [weppos/whois.js#1]
@weppos Would it be possible to transfer ownership of this module for continued support?

I'd like to integrate `whoisjs` rather than `exec`-ing out to Ruby, for example.

**Comment by Schoonology** [comment]
... or some other module. Either way, it'd be nice to have a Node-only, multi-TLD whois client, and am more than comfortable turning this into a working solution.

**Comment by hjr265** [comment]
@weppos I am the developer of [node-whois](https://www.npmjs.com/package/node-whois) and I was asked by one of its users to "[Ask @weppos nicely for 'whois](https://github.com/hjr265/node-whois/issues/21)".

Let me know what you think. In case you do not plan to continue working on this package anymore, it would be really appreciated if you could [transfer ownership](https://docs.npmjs.com/cli/owner) of "whois" on https://www.npmjs.com to [me](https://www.npmjs.com/~hjr265).

**Comment by weppos** [comment]
RE: https://github.com/hjr265/node-whois/issues/21

@hjr265 Given I trust @mikemaccana judgement, your lib currently seems to be the most popular whois lib in Node.js, I haven't been using the Node.js whois namespace at all and I'm not planning to write a lot of JS code, I'll be happy to release the namespace to you.

Please give me some time to check the docs on how to make it happen. Feel free to ping me in a few days if I will forget it.

As a side note, I'm happy to release the name space to you as long as you agree to do the same in the future if you should stop working on your lib and someone else will come with a better solution. It's never a good idea to keep a good package name in hostage (and I blame myself as I've done it for so long).

**Comment by hjr265** [comment]
@weppos It's a deal! :smile: I won't hold onto the package name unless I continue to work on the library. And, thank you for doing this!

**Comment by weppos** [comment]
Done. https://www.npmjs.com/package/whois

**Comment by hjr265** [comment]
@weppos Thank you :smile:
